### ISSUE TITLE
Installation fails with "fatal error C1083: Cannot open compiler generated file" on Windows 11

### ISSUE THREAD

**Issue by 917940234** [IDEA-Research/Grounded-Segment-Anything#101]
### Environment:
OS: Windows 11
Python version: 3.9
CUDA version: 11.8
Installed Tools: MSVC v143 - VS 2022 C++ x64/x86 build tools, Windows 11 SDK (10.0.22000.0)
![image](https://user-images.githubusercontent.com/86662143/231434326-e7fdea15-4461-43f8-beeb-724200411c7e.png)
![image](https://user-images.githubusercontent.com/86662143/231434415-61a82c20-3b9a-4002-95ad-bf0bd5ec705e.png)
### Description:
When running the installation command python -m pip install -e GroundingDINO, the following error occurs:
```shell
C:\SyncSpace\IdeaStorm\PycharmProjects\Grounded-Segment-Anything\GroundingDINO\groundingdino\models\GroundingDINO\csrc\MsDeformAttn\ms_deform_attn_cpu.cpp : fatal error C1083: Cannot open compiler generated file: “”: Invalid argument
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
```
I am not able to install the project due to this error.
![image](https://user-images.githubusercontent.com/86662143/231435037-88530b14-bd88-4f04-9a33-3083745b75be.png)
### Steps to reproduce:
1. clone项目
2. 创建conda环境-python3.9
3. [Microsoft C++ 生成工具](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)
4. [groundingdino_swint_ogc.pth](https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth)
5. `conda install -c conda-forge pycocotools`
6. `pip install -r requirements.txt`
7. `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`
8. `python -m pip install -e segment_anything`
9. `python -m pip install -e GroundingDINO`（error）
### Expected behavior:
The installation should complete successfully without any errors.
### Actual behavior:
The installation fails with the mentioned error, and I am unable to proceed with the project setup.
Any help or suggestions to fix this issue would be appreciated.

**Comment by SlongLiu** [comment]
看起来是缺乏某个编译器导致的。我们再看一下。

**Comment by 917940234** [comment]
Resolved! The core issue was related to the directory structure. When Ninja builds the output, it repeats the previous absolute paths, which generally results in very long paths. My project was nested within three folders, and the characters in these folder names were doubled, resulting in a long path. By shortening the project name and ensuring that it stayed within 260 characters, I was able to resolve the issue. The C++ version doesn't appear to be the primary problem, as the current version has been verified to work. But I still didn't end up running it successfully...

**Comment by 917940234** [comment]
The final process I ran successfully was as follows：
## 快速入门
1. clone项目
2. 创建conda环境-python3.9
3. [Microsoft C++ 生成工具](https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/)
4. [groundingdino_swint_ogc.pth](https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth)
5. `conda install -c conda-forge pycocotools`
6. `pip install -r requirements.txt`
7. `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge`
9. `python -m pip install -e segment_anything`
10. `python -m pip install -e GroundingDINO`
11. `pip install --upgrade diffusers[torch]`
12. `pip install opencv-python pycocotools matplotlib onnxruntime onnx ipykernel`
### 运行 Grounding DINO Demo
```
$env:CUDA_VISIBLE_DEVICES = "0"
python grounding_dino_demo.py --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py --grounded_checkpoint groundingdino_swint_ogc.pth --input_image assets/demo1.jpg --output_dir "outputs" --box_threshold 0.3 --text_threshold 0.25 --text_prompt "bear" --device "cuda"
```
