### ISSUE TITLE
Can we get a pixel-wise label map?

### ISSUE THREAD

**Issue by PoopBear1** [IDEA-Research/Grounded-Segment-Anything#107]
Thank you for developing such fantastic work!

Can I get some hints on how we can get a pixel-wise label map once we obtain the JSON file and the mask?

Sorry if this is a silly question.

I did not figure out how can I directly archive that goal with some bounding box only.

e.g. get bear as '1' in pixel-level and '0' for other pixels.
![image](https://user-images.githubusercontent.com/36417130/231519545-f6241be9-60fb-4f06-9a53-9ed493622022.png)
and
![image](https://user-images.githubusercontent.com/36417130/231516453-d2ba8584-a98a-4d46-bb80-e2c78b450f31.png)

Any help would be much appreciated.

**Comment by Andy1621** [comment]
Thanks for your question! You can change the code for saving the pixel-wise label. It may be better to directly save the mask_img. I have changed it to plt for visualization.
https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/816ddd3b10a3f4aef7a1ffc02e60d19b4f1b6f9f/automatic_label_demo.py#L163-L169
