### ISSUE TITLE
为什么运行了gradio_app.py后，提示的local网页打不开，share的能打开，需要怎么做才能打开local_URL

### ISSUE THREAD

**Issue by 16952280536** [IDEA-Research/Grounded-Segment-Anything#115]
![1](https://user-images.githubusercontent.com/73433395/231739955-6228b890-02f5-4bbe-af90-ebcd1aa9be6b.jpg)
![12](https://user-images.githubusercontent.com/73433395/231740071-3c057948-510f-4113-8803-0978bc106253.jpg)

**Comment by rentainhe** [comment]
或许可以尝试修改IP地址为 127.0.0.1试试

**Comment by 16952280536** [comment]
> 或许可以尝试修改IP地址为 127.0.0.1试试

确实可以哈哈哈，谢谢
