### ISSUE TITLE
osx_l_wo_decoder.pth.tar no longer available at google drive link has it been renamed?

### ISSUE THREAD

**Issue by johndavidbustard** [IDEA-Research/Grounded-Segment-Anything#144]
The osx_l_wo_decoder.pth.tar is no longer available at google drive link (https://drive.google.com/drive/folders/1x7MZbB6eAlrq5PKC9MaeIm4GqkBpokow) described on the front page has it been renamed?

**Comment by linjing7** [comment]
Hi, thanks for your interest in our work. I will upload this file tomorrow.

**Comment by linjing7** [comment]
Hi, we have uploaded the pretrained model.
