### ISSUE TITLE
Docker failed

### ISSUE THREAD

**Issue by Luoyu-Wang** [IDEA-Research/Grounded-Segment-Anything#184]
We installed based on docker, but failed.  Could you tell me that how to solve the problem? Thanks.
...
=> exporting to image                                                     3.1s
 => => exporting layers                                                    3.1s
 => => writing image sha256:c937884c36f1c2a5ab9634f3be74937a021aa540a0b82  0.0s
 => => naming to docker.io/library/gsa:v0                                  0.0s
nvidia-docker run --gpus all -it --rm --net=host --privileged \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e DISPLAY=ISPLAY \
-v /home/wly/Downloads/Grounded-Segment-Anything-main:/home/appuser \
--name=gsa \
--ipc=host -it gsa:v0
make: nvidia-docker: Command not found
Makefile:5: recipe for target 'run' failed
make: *** [run] Error 127

We also try dcoker run, but also failed. 

 $ docker run --gpus all -it --rm --net=host --privileged \
> -v /tmp/.X11-unix:/tmp/.X11-unix \
> -e DISPLAY=ISPLAY \
> -v /home/wly/Downloads/Grounded-Segment-Anything-main:/home/appuser \
> --name=gsa \
> --ipc=host -it gsa:v0
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by JiahaoXia** [comment]
Same error here. Does anyone fix this issue?

**Comment by JunzheJosephZhu** [comment]
see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.8.0/install-guide.html
