### ISSUE TITLE
The guy who can sing, dance, rap and play basketball?

### ISSUE THREAD

**Issue by Roger2148** [IDEA-Research/Grounded-Segment-Anything#200]
In the example images, does anyone know the name of the guy who can sing, dance, rap and play basketball? (Chicken)

**Comment by distort5871** [comment]
> In the example images, does anyone know the name of the guy who can sing, dance, rap and play basketball? (Chicken)

small black one, your chicken feet exposed

**Comment by lastwhisper-ghy** [comment]
So abstract
