### ISSUE TITLE
[Attention] CHATBOT默认调用的语言模型是DAVINCI，会产生费用，大家注意使用

### ISSUE THREAD

**Issue by AreChen** [IDEA-Research/Grounded-Segment-Anything#201]
昨天用了很久晚上一看账单惊呆了，发现一直调用的DAVINCI，这只是其中一小部分的截图
![image](https://user-images.githubusercontent.com/20765464/234449299-b0263df3-50e0-4917-bbb3-f910e569d485.png)

**Comment by Andy1621** [comment]
感谢你的提问，chatbot是基于[visual-chatgpt](https://github.com/microsoft/TaskMatrix/blob/main/visual_chatgpt.py)开发的。使用的langchain默认调用的确实是davinci。
https://github.com/hwchase17/langchain/blob/f4829025fee0f07169000e42bd8e8185ca830673/langchain/llms/openai.py#L119-L124

**Comment by rentainhe** [comment]
我们tag了一个notice，为了用户可以注意到这个部分

**Comment by AreChen** [comment]
能帮助到后面的人就好！

**Comment by Nidacoke** [comment]
#50

**Comment by Nidacoke** [comment]
#50
