### ISSUE TITLE
Run Grounded-Segment-Anything + Tag2Text Demo

### ISSUE THREAD

**Issue by Ziord01** [IDEA-Research/Grounded-Segment-Anything#204]
I'm having trouble running the demo：
![1682492279742](https://user-images.githubusercontent.com/40163674/234494783-1353adeb-1d03-436d-b975-dc8562d5abcf.png)

**Comment by rentainhe** [comment]
Thanks for reporting this issue, we will figure out this bug later with @xinyu1205

**Comment by Ziord01** [comment]
ok，vrey thanks @xinyu1205
