### ISSUE TITLE
辛苦了 作者，下载HF进不去了，能不能BLIP和tag2text模型上传？

### ISSUE THREAD

**Issue by dream-desktop** [IDEA-Research/Grounded-Segment-Anything#231]
huggingface从8号起 进不去了，模型无法下载。

**Comment by rentainhe** [comment]
> huggingface从8号起 进不去了，模型无法下载。

哈喽您好，这边我也遇到了类似的huggingface进不去的问题，这边其实是huggingface官方换了新的证书需要更新一下，就可以解决这个问题了

**Comment by dream-desktop** [comment]
> > huggingface从8号起 进不去了，模型无法下载。
> 
> 哈喽您好，这边我也遇到了类似的huggingface进不去的问题，这边其实是huggingface官方换了新的证书需要更新一下，就可以解决这个问题了

谢谢回答，我是小白，不太懂，怎么更新呢，能不能具体告诉一下。

**Comment by hukaick** [comment]
https://github.com/positive666/Prompt-Can-Anything   我参考的这个项目

**Comment by dream-desktop** [comment]
> https://github.com/positive666/Prompt-Can-Anything 我参考的这个项目

谢谢大佬的回答，可是我想问的是有什么办法能进去huggingface官网。

**Comment by rentainhe** [comment]
> huggingface从8号起 进不去了，模型无法下载。

这边我也研究一下 ，因为我也没有解决这个问题目前 (
