### ISSUE TITLE
设置cuda:1 后 grounded 结果为空。

### ISSUE THREAD

**Issue by xujin1184104394** [IDEA-Research/Grounded-Segment-Anything#247]
设置device = "cuda:1" 但是get_grounding_output 得到的模型结果是空的。 而我用device = "cuda:0"结果是正常的。

**Comment by rentainhe** [comment]
Thanks for reporting this issue, we will check it later

**Comment by xujin1184104394** [comment]
hi，问一下，你们这边demo上可以尝试使用cuda:1或者其它非cuda:0推理出正确结果吗？

**Comment by rentainhe** [comment]
> hi，问一下，你们这边demo上可以尝试使用cuda:1或者其它非cuda:0推理出正确结果吗？

这里的原因是因为Deformable-Attention算子目前无法支持类似`cuda:1`这样的设置，可以考虑使用`CUDA_VISIBLE_DEVICES=1` + `cuda:0`来绕开这个问题，关于算子部分的bug，我们暂时没有解决，有需要的话可以尝试联系Deformable-Attention的作者看看相关问题
