### ISSUE TITLE
Please rollback to 00b2c30

### ISSUE THREAD

**Issue by xueli-sherryli** [IDEA-Research/Grounded-Segment-Anything#25]
Some unexpected errors happened after the pull requests and sorry for my ignoring them before the pull requests.
Please rollback to 00b2c30

**Comment by rentainhe** [comment]
> Some unexpected errors happened after the pull requests and sorry for my ignoring them before the pull requests. Please rollback to [00b2c30](https://github.com/IDEA-Research/Grounded-Segment-Anything/commit/00b2c303d727aadcd13fd47680c3c88b96600094)

You can submit a new PR to fix this~

**Comment by rentainhe** [comment]
We've already reset the version~

**Comment by xueli-sherryli** [comment]
THANKA!
