### ISSUE TITLE
Is this Model/project free for commercial purposes?

### ISSUE THREAD

**Issue by wqh17101** [IDEA-Research/Grounded-Segment-Anything#272]
Including the [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO) checkpoints and the project codes.

**Comment by rentainhe** [comment]
Our license is `Apache 2.0`, which allows you to use our model weights and project within the scope of the license. However, if our project includes models from other projects, it is necessary to review the requirements specified by each individual project.

**Comment by wqh17101** [comment]
OK , thank you. @rentainhe

**Comment by rentainhe** [comment]
> OK , thank you. @rentainhe

You're welcome!
