### ISSUE TITLE
fail to import _C modul from groundingdino

### ISSUE THREAD

**Issue by kobic8** [IDEA-Research/Grounded-Segment-Anything#275]
this error occured when I run the demo, 
GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py

**Comment by rentainhe** [comment]
Hello! Maybe you did not successfully install GroundingDINO custom operator

We need CUDA Runtime to compline specific Deformable-Attention operator, you should make sure `CUDA_HOME` is not `None` before installing GroundingDINO, after that, you can remore `/build` dir and re-install grounding dino again

**Comment by LiaoZihZrong** [comment]
build gino again, and i fix, i don't why 
`python -m pip install -e GroundingDINO`

**Comment by WorasitJ** [comment]
> build gino again, and i fix, i don't why `python -m pip install -e GroundingDINO`

this is work.
