### ISSUE TITLE
Q: why not use GroundingDINO as git submodule?

### ISSUE THREAD

**Issue by worldwalk** [IDEA-Research/Grounded-Segment-Anything#280]
hi,

I'm wondering why not just use GroundingDINO(https://github.com/IDEA-Research/GroundingDINO) as submodule in this project? 
is there difference btw the GroundingDINO repo and GroundingDINO directory here?  are they synced?

thanks a lot!

**Comment by rentainhe** [comment]
> hi,
> 
> I'm wondering why not just use GroundingDINO(https://github.com/IDEA-Research/GroundingDINO) as submodule in this project? is there difference btw the GroundingDINO repo and GroundingDINO directory here? are they synced?
> 
> thanks a lot!

There's almost no difference, we only modified some visualization function under `/Grounded-Segment-Anything/GroundingDINO`, we just only forgot to make it as a submodule lol

**Comment by worldwalk** [comment]
wonderful work! thanks!
