### ISSUE TITLE
Installation fails with Error checking compiler version for cl: [WinError 2] The system cannot find the file specified warnings.warn(f'Error checking compiler version for {compiler}: {error}')

### ISSUE THREAD

**Issue by Delvach** [IDEA-Research/Grounded-Segment-Anything#282]
Start SAM Processing
Installing sd-webui-segment-anything requirement: groundingdino
Traceback (most recent call last):
  File "C:\sd\extensions\sd-webui-segment-anything\scripts\dino.py", line 36, in install_goundingdino
    launch.run_pip(
  File "C:\sd\launch.py", line 143, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "C:\sd\launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
Command: "C:\sd\venv\Scripts\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/IDEA-Research/GroundingDINO
  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\ben\appdata\local\temp\pip-req-build-74l4pg_9
  Resolved https://github.com/IDEA-Research/GroundingDINO to commit 31aa788a3cf6ab82d27385f39e242b34af9cc011
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: torch in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (2.0.1+cu118)
Requirement already satisfied: torchvision in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (0.15.2+cu118)
Requirement already satisfied: transformers in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (4.25.1)
Requirement already satisfied: addict in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: yapf in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (0.33.0)
Requirement already satisfied: timm in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (0.6.7)
Requirement already satisfied: numpy in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (1.23.5)
Requirement already satisfied: opencv-python in c:\sd\venv\lib\site-packages (from groundingdino==0.1.0) (4.7.0.72)
Collecting supervision==0.6.0 (from groundingdino==0.1.0)
  Using cached supervision-0.6.0-py3-none-any.whl (31 kB)
Collecting pycocotools (from groundingdino==0.1.0)
  Using cached pycocotools-2.0.6-cp310-cp310-win_amd64.whl
Requirement already satisfied: matplotlib in c:\sd\venv\lib\site-packages (from supervision==0.6.0->groundingdino==0.1.0) (3.7.1)
Requirement already satisfied: filelock in c:\sd\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.12.0)
Requirement already satisfied: typing-extensions in c:\sd\venv\lib\site-packages (from torch->groundingdino==0.1.0) (4.6.2)
Requirement already satisfied: sympy in c:\sd\venv\lib\site-packages (from torch->groundingdino==0.1.0) (1.12)
Requirement already satisfied: networkx in c:\sd\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.1)
Requirement already satisfied: jinja2 in c:\sd\venv\lib\site-packages (from torch->groundingdino==0.1.0) (3.1.2)
Requirement already satisfied: requests in c:\sd\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (2.25.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\sd\venv\lib\site-packages (from torchvision->groundingdino==0.1.0) (9.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.14.1)
Requirement already satisfied: packaging>=20.0 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (2023.5.5)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in c:\sd\venv\lib\site-packages (from transformers->groundingdino==0.1.0) (4.65.0)
Requirement already satisfied: tomli>=2.0.1 in c:\sd\venv\lib\site-packages (from yapf->groundingdino==0.1.0) (2.0.1)
Requirement already satisfied: fsspec in c:\sd\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers->groundingdino==0.1.0) (2023.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (4.39.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\sd\venv\lib\site-packages (from matplotlib->supervision==0.6.0->groundingdino==0.1.0) (2.8.2)
Requirement already satisfied: colorama in c:\sd\venv\lib\site-packages (from tqdm>=4.27->transformers->groundingdino==0.1.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\sd\venv\lib\site-packages (from jinja2->torch->groundingdino==0.1.0) (2.1.2)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\sd\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\sd\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\sd\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\sd\venv\lib\site-packages (from requests->torchvision->groundingdino==0.1.0) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\sd\venv\lib\site-packages (from sympy->torch->groundingdino==0.1.0) (1.3.0)
Requirement already satisfied: six>=1.5 in c:\sd\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->supervision==0.6.0->groundingdino==0.1.0) (1.16.0)
Building wheels for collected packages: groundingdino
  Building wheel for groundingdino (setup.py): started
  Building wheel for groundingdino (setup.py): finished with status 'error'
  Running setup.py clean for groundingdino
Failed to build groundingdino

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\ben\AppData\Local\Temp\pip-req-build-74l4pg_9'
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [53 lines of output]
  Building wheel groundingdino-0.1.0
  Compiling with CUDA
  running bdist_wheel
  C:\sd\venv\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\version.py -> build\lib.win-amd64-cpython-310\groundingdino
  copying groundingdino\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino
  creating build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinB_cfg.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\GroundingDINO_SwinT_OGC.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  copying groundingdino\config\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\config
  creating build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\transforms.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  copying groundingdino\datasets\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\datasets
  creating build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\registry.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  copying groundingdino\models\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models
  creating build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\box_ops.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\get_tokenlizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\inference.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\logger.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\misc.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slconfig.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\slio.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\time_counter.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\visualizer.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\vl_utils.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  copying groundingdino\util\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\util
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\bertwarper.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\fuse_modules.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\groundingdino.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\ms_deform_attn.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\transformer_vanilla.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\utils.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  copying groundingdino\models\GroundingDINO\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO
  creating build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\backbone.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\position_encoding.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\swin_transformer.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  copying groundingdino\models\GroundingDINO\backbone\__init__.py -> build\lib.win-amd64-cpython-310\groundingdino\models\GroundingDINO\backbone
  running build_ext
  C:\sd\venv\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  error: [WinError 2] The system cannot find the file specified
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for groundingdino
ERROR: Could not build wheels for groundingdino, which is required to install pyproject.toml-based projects

None
GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.

**Comment by rentainhe** [comment]
Hello, maybe you can install `ninja` and try again to see if there's still the same issue

**Comment by Delvach** [comment]
That did it! I figured that out about 20 minutes after creating the ticket. Installed ninja, updated my path and it worked perfectly. I should've read the log more carefully. Thanks!

**Comment by jdiazram** [comment]
> That did it! I figured that out about 20 minutes after creating the ticket. Installed ninja, updated my path and it worked perfectly. I should've read the log more carefully. Thanks!

Can you explain how to do that? I have the same issue. Thx

**Comment by LuoRiChangHong-2** [comment]
I have installed ninja but still facing the following issue:
running build_ext
      C:\Users\yyLiu\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]
Thank you very much if anyone can help me!
