### ISSUE TITLE
Running gradio_app.py successfully (without any errors) but cannot open the URL (showing This site can’t be reached)

### ISSUE THREAD

**Issue by JiuyiX** [IDEA-Research/Grounded-Segment-Anything#283]
I just run the code in Gradio App successfully and the terminal output a local URL (i.e. 0.0.0.0: 7589). It shows "This site can't be reached" when I try to open it in Chrome. Has anyone met this issue?

**Comment by JiuyiX** [comment]
> > I just run the code in Gradio App successfully and the terminal output a local URL (i.e. 0.0.0.0: 7589). It shows "This site can't be reached" when I try to open it in Chrome. Has anyone met this issue?
> 
> You can try to use the ip of your machine and restart the gradio app again

I use shart-link to open it successfully. However, the API cannot generate image normally when I use the demo image (it shows "error" after processing about 4 seconds every time). Can you give me some hints on this issue?

**Comment by rentainhe** [comment]
> > > I just run the code in Gradio App successfully and the terminal output a local URL (i.e. 0.0.0.0: 7589). It shows "This site can't be reached" when I try to open it in Chrome. Has anyone met this issue?
> > 
> > 
> > You can try to use the ip of your machine and restart the gradio app again
> 
> I use shart-link to open it successfully. However, the API cannot generate image normally when I use the demo image (it shows "error" after processing about 4 seconds every time). Can you give me some hints on this issue?

Is there any error info in your terminal? Would you like to share us more information about the error

**Comment by JiuyiX** [comment]
> > > > I just run the code in Gradio App successfully and the terminal output a local URL (i.e. 0.0.0.0: 7589). It shows "This site can't be reached" when I try to open it in Chrome. Has anyone met this issue?
> > > 
> > > 
> > > You can try to use the ip of your machine and restart the gradio app again
> > 
> > 
> > I use shart-link to open it successfully. However, the API cannot generate image normally when I use the demo image (it shows "error" after processing about 4 seconds every time). Can you give me some hints on this issue?
> 
> Is there any error info in your terminal? Would you like to share us more information about the error

Just resolved this problem. Thanks a lot.

**Comment by jloveric** [comment]
@JiuyiX what was your resolution to the final problem? I think I have a similar error, whenever I execute on the default image I eventually get an error https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/459

**Comment by prrw** [comment]
> > > > > I just run the code in Gradio App successfully and the terminal output a local URL (i.e. 0.0.0.0: 7589). It shows "This site can't be reached" when I try to open it in Chrome. Has anyone met this issue?
> > > > 
> > > > 
> > > > You can try to use the ip of your machine and restart the gradio app again
> > > 
> > > 
> > > I use shart-link to open it successfully. However, the API cannot generate image normally when I use the demo image (it shows "error" after processing about 4 seconds every time). Can you give me some hints on this issue?
> > 
> > 
> > Is there any error info in your terminal? Would you like to share us more information about the error
> 
> Just resolved this problem. Thanks a lot.

Heyyy how did you solve this. I am also getting connection error when i click on Gradio app.
@rentainhe @JiuyiX
