### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by CodePainter-Swang** [IDEA-Research/Grounded-Segment-Anything#286]
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/133226638/fc56f1e8-95b9-4935-ad95-39ae61d42142)
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/133226638/3a798194-b7a9-4e28-8da9-84f39a43a3b8)
Do you have encountered the same problem? I can run it a week ago ,but now i can not run it correctly!

**Comment by rentainhe** [comment]
it seems the network error

**Comment by bestharm** [comment]
but i can not solve it。。。-------- 原始邮件 --------发件人： Ren Tianhe ***@***.***>日期： 2023年5月31日周三 下午1:26收件人： IDEA-Research/Grounded-Segment-Anything ***@***.***>抄送： bestharm ***@***.***>, Author ***@***.***>主    题： Re: [IDEA-Research/Grounded-Segment-Anything] ConnectionResetError: [Errno 104] Connection reset by peer (Issue #286)
it seems the network error

**Comment by shaun17** [comment]
try to download the model bert-base-uncased in your local, method here 
https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/75#issuecomment-1508225437

change a way to get bert-base-uncased

**Comment by bestharm** [comment]
ok， i will do it ，thanks for your great help！！！-------- 原始邮件 --------发件人： shxxn ***@***.***>日期： 2023年5月31日周三 下午1:45收件人： IDEA-Research/Grounded-Segment-Anything ***@***.***>抄送： bestharm ***@***.***>, Author ***@***.***>主    题： Re: [IDEA-Research/Grounded-Segment-Anything] ConnectionResetError: [Errno 104] Connection reset by peer (Issue #286)
try to download the model bert-base-uncased in your local, method here
#75 (comment)
change a way to get bert-base-uncased
