### ISSUE TITLE
Instance segmentation does not work to show objects with different colors

### ISSUE THREAD

**Issue by HripsimeS** [IDEA-Research/Grounded-Segment-Anything#293]
Hello. I was checking your code and it seems it is doing an instance segmentation with bounding boxes.
https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_simple_demo.py

But then I could not see there a visualization of the segmentation of each instance of the same class. I saw your example on "bear" when it segment each bear with different color and I was supposing it is an instance segmentation.

For for trees I received a segmentation, but all of them with the same color. It seems a semantic segmentation.
Can you please recommend me what I should modify in order to get each tree with a different color segmented.

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/42246765/8f11bb42-4c8a-4fd6-8d20-2c036aed2d6d)

![mask](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/42246765/2d718446-6a4d-49e8-81b3-60cfaf4b9301)

**Comment by rentainhe** [comment]
> Hello. I was checking your code and it seems it is doing an instance segmentation with bounding boxes. https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_simple_demo.py
> 
> But then I could not see there a visualization of the segmentation of each instance of the same class. I saw your example on "bear" when it segment each bear with different color and I was supposing it is an instance segmentation.
> 
> For for trees I received a segmentation, but all of them with the same color. It seems a semantic segmentation. Can you please recommend me what I should modify in order to get each tree with a different color segmented.
> 
> ![image](https://user-images.githubusercontent.com/42246765/243694327-8f11bb42-4c8a-4fd6-8d20-2c036aed2d6d.png)
> 
> ![mask](https://user-images.githubusercontent.com/42246765/243726773-2d718446-6a4d-49e8-81b3-60cfaf4b9301.jpg)

Sorry, we use supervision repo to simplify the demo code, which not output different color for each instance, you can try to use our original code to generate different color: https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_demo.py

**Comment by HripsimeS** [comment]
@rentainhe thank you very much. I removed the part that doing a box annotation to get only mask segmentation.

annotated_image = mask_annotator.annotate(scene=image.copy(), detections=detections)
#annotated_image = box_annotator.annotate(scene=annotated_image, detections=detections, labels=labels)

In attached you can see the example of extracted one instance. How I can keep the RGB part of segmented instances and all other parts just make black? How to extract the pixel of each instance and make a visualization like in this example?

Thank you very much in advance!!!

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/42246765/1b5250e0-1cdf-4eef-b8fb-2fdd1f378301)

**Comment by HripsimeS** [comment]
@rentainhe I found a way how to do it, the solution is below and it looks good for me!

mask = np.asarray(Image.fromarray(detections.mask[0]))
expanded_mask = np.expand_dims(mask, axis=2)
result= expanded_mask * np.asarray(image)
result_img = Image.fromarray(result.astype(np.uint8))
plt.imshow(result_img)
plt.axis('off')
plt.show()

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/42246765/e918d632-40a0-4fb4-aaba-ff1c95f5f59a)
