### ISSUE TITLE
Swin L model

### ISSUE THREAD

**Issue by yoyoyo-yo** [IDEA-Research/Grounded-Segment-Anything#296]
Thank you for sharing nice solution!

Can I use Swin-L ?

**Comment by rentainhe** [comment]
> Thank you for sharing nice solution!
> 
> Can I use Swin-L ?

Sry we did not release Swin-L Grounding-DINO model yet, maybe you can try to use Swin-B for better performance

**Comment by rentainhe** [comment]
I'm going to close this issue now, feel free to reopen it or report a new issue anytime you need help
