### ISSUE TITLE
HQ-SAM + RAM

### ISSUE THREAD

**Issue by quantingxie** [IDEA-Research/Grounded-Segment-Anything#302]
Hi,

Will you release the code for HQ-SAM with RAM?

**Comment by rentainhe** [comment]
Yes for sure! We will update it recently

**Comment by rentainhe** [comment]
We've implement HQ-SAM in [grounded_sam_demo.py](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam_demo.py) you can try it for better prediction in some cases

**Comment by rentainhe** [comment]
HQ-SAM + RAM has already been supported and tested under Grounded-SAM, you can try it with this two demos:

- https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/automatic_label_ram_demo.py
- https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/automatic_label_simple_demo.py

@quantingxie

**Comment by quantingxie** [comment]
Thank you!
