### ISSUE TITLE
[Solved] GroundingDINO设置特定device后没有Box预测结果

### ISSUE THREAD

**Issue by jiachen0212** [IDEA-Research/Grounded-Segment-Anything#303]
没有小伙伴发现吗  cpu下可检出box， cuda模式无法检出... ???

**Comment by rentainhe** [comment]
> 没有小伙伴发现吗 cpu下可检出box， cuda模式无法检出... ???

哈喽！话说你有设置特别的cuda device吗，例如 "cuda:2" 这样的设置，这个可能会有bug，deformable attention算子无法支持这样的设置

**Comment by jiachen0212** [comment]
> > 没有小伙伴发现吗 cpu下可检出box， cuda模式无法检出... ???
> 
> 哈喽！话说你有设置特别的cuda device吗，例如 "cuda:2" 这样的设置，这个可能会有bug，deformable attention算子无法支持这样的设置
> 
> 如果需要设置特别的device的话可以:
> 
> ```shell
> export CUDA_VISIBLE_DEVICES=2
> python grounded_sam_demo.py
> `` 
感谢 我刚也发现他默认调用cuda:0  ~  设置下ok的  这个潜在bug好隐晦/.///

**Comment by rentainhe** [comment]
> > > 没有小伙伴发现吗 cpu下可检出box， cuda模式无法检出... ???
> > 
> > 
> > 哈喽！话说你有设置特别的cuda device吗，例如 "cuda:2" 这样的设置，这个可能会有bug，deformable attention算子无法支持这样的设置
> > 如果需要设置特别的device的话可以:
> > ```shell
> > export CUDA_VISIBLE_DEVICES=2
> > python grounded_sam_demo.py
> > `` 
> > ```
> 
> 感谢 我刚也发现他默认调用cuda:0 ~ 设置下ok的 这个潜在bug好隐晦/.///

是的，我们会单独Pin一个issue highlight这个问题

**Comment by SauceCat** [comment]
なるほど！！！debug了好久才发现把cuda:6换回去cuda就没有问题了。感谢感谢。 💯
