### ISSUE TITLE
support of DINO2 for bbox+labels

### ISSUE THREAD

**Issue by kobic8** [IDEA-Research/Grounded-Segment-Anything#309]
Hello,
are you planning on integrating DINO-2 for faster and more accurate results for bbox+labels?

**Comment by rentainhe** [comment]
Do you mean using dinov2 or not? As I know it's a self-supervised model and may not that suitable for this task

**Comment by kobic8** [comment]
IDEA-Research did an awesome work building Grounded-DINO which is based on DINO (version1), I was asking if you also plan to build, enrich the grounded-model to DINO-2

**Comment by rentainhe** [comment]
> IDEA-Research did an awesome work building Grounded-DINO which is based on DINO (version1), I was asking if you also plan to build, enrich the grounded-model to DINO-2

Actually they're different works lol, GroundingDINO is built on [DINO](https://github.com/IDEA-Research/DINO) from IDEA-Research which has the same name as dino but a detection model

**Comment by kobic8** [comment]
WOW!!! a bit confusing, since this model has the same name as [Meta/DINO](https://github.com/facebookresearch/dino)
so for now, the base model of G-DINO has not future work of improvment? 
are you planning of releasing a code of fine-tuning the model? I have an issue that I want to solve: 
I have a maritime dataset of boats, jet-skis and other seaborne vehicles. G-DINO detects and labels the targets as boat/ship, but I am interested in refinement to teach the model about the boats' names

**Comment by rentainhe** [comment]
> WOW!!! a bit confusing, since this model has the same name as [Meta/DINO](https://github.com/facebookresearch/dino) so for now, the base model of G-DINO has not future work of improvment? are you planning of releasing a code of fine-tuning the model? I have an issue that I want to solve: I have a maritime dataset of boats, jet-skis and other seaborne vehicles. G-DINO detects and labels the targets as boat/ship, but I am interested in refinement to teach the model about the boats' names

We did not plan to release the training and fine-tuning code because our paper is still under review and the code is massive and needs to be cleaned, it's a hard job, but we did not have much time to do it now.

**Comment by rentainhe** [comment]
I'm going to close this issue now, feel free to reopen it if needed
