### ISSUE TITLE
Suggestion - update the pipeline to Fast-Sam in order to achieve real time inference

### ISSUE THREAD

**Issue by ofirkris** [IDEA-Research/Grounded-Segment-Anything#314]
Reference - https://github.com/CASIA-IVA-Lab/FastSAM

<img width="831" alt="image" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/9070477/9dfd0b02-1d43-4aa0-b9ee-1be73029c971">

**Comment by rentainhe** [comment]
> Reference - https://github.com/CASIA-IVA-Lab/FastSAM
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/9070477/248240021-9dfd0b02-1d43-4aa0-b9ee-1be73029c971.png">

Thanks for your suggestion, we will implement fast-sam into Grounded-SAM in the future release~

**Comment by rentainhe** [comment]
> Reference - https://github.com/CASIA-IVA-Lab/FastSAM
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/9070477/248240021-9dfd0b02-1d43-4aa0-b9ee-1be73029c971.png">

We've simply implement Grounded-FastSAM here: https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM, but it's still under developed
