### ISSUE TITLE
Suggestion - Integrate MobileSAM into the pipeline for lightweight and faster inference

### ISSUE THREAD

**Issue by qiaoyu1002** [IDEA-Research/Grounded-Segment-Anything#322]
Reference: https://github.com/ChaoningZhang/MobileSAM

Our project performs on par with the original SAM and keeps exactly the same pipeline as the original SAM except for a change on the image encode, therefore, it is easy to Integrate into any project.

MobileSAM is around 60 times smaller and around 50 times faster than original SAM, and it is around 7 times smaller and around 5 times faster than the concurrent FastSAM. The comparison of the whole pipeline is summarzed as follows:

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/ecc801de-a7c9-4ccb-84f7-477e359a1892)

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/102718175/39f257e2-dca0-4956-bdb1-4326e6b5d13b)

**Comment by rentainhe** [comment]
> Reference: https://github.com/ChaoningZhang/MobileSAM
> 
> Our project performs on par with the original SAM and keeps exactly the same pipeline as the original SAM except for a change on the image encode, therefore, it is easy to Integrate into any project.
> 
> MobileSAM is around 60 times smaller and around 50 times faster than original SAM, and it is around 7 times smaller and around 5 times faster than the concurrent FastSAM. The comparison of the whole pipeline is summarzed as follows:
> 
> ![image](https://user-images.githubusercontent.com/102718175/249313774-ecc801de-a7c9-4ccb-84f7-477e359a1892.png)
> 
> ![image](https://user-images.githubusercontent.com/102718175/249313309-39f257e2-dca0-4956-bdb1-4326e6b5d13b.png)

Nice work! We will implement Grounded-MobileSAM into Grounded-Segment-Anything recently

**Comment by rentainhe** [comment]
We've already implemented it here: [Grounded-MobileSAM](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/EfficientSAM#run-grounded-mobilesam-demo) and highlight it in our README @qiaoyu1002

**Comment by qiaoyu1002** [comment]
Thanks a lot.

**Comment by rentainhe** [comment]
> Thanks a lot.

You're welcome! We will try to build more demo on it

**Comment by rentainhe** [comment]
And I'm going to close this issue, any updates you can open a new issue to inform me or send me an email
