### ISSUE TITLE
name 'build_sam_hq' is not defined

### ISSUE THREAD

**Issue by MrTHMX** [IDEA-Research/Grounded-Segment-Anything#328]
When I try run grounded-sam demo with sam-hq, the error is 
194 in <module>                                                            │
│                                                                                 │
│   191 │                                                                         │
│   192 │   # initialize SAM                                                      │
│   193 │   if use_sam_hq:                                                        │
│ ❱ 194 │   │   predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoin │
│   195 │   else:                                                                 │
│   196 │   │   predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to( │
│   197 │   image = cv2.imread(image_path)           
NameError: name 'build_sam_hq' is not defined

**Comment by rentainhe** [comment]
We've updated the `segment_anything` dir, you should reinstall sam before running the demo

**Comment by MrTHMX** [comment]
> We've updated the dir, you should reinstall sam before running the demo`segment_anything`
Thank you very much for your reply, but I think I have reinstalled

**Comment by MrTHMX** [comment]
> We've updated the `segment_anything` dir, you should reinstall sam before running the demo

After I tried to re-download, the problem changed to "filename 'storages' not found"
190 │                                                                                          │
│   191 │   # initialize SAM                                                                       │
│   192 │   if use_sam_hq:                                                                         │
│ ❱ 193 │   │   predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(device))    │
│   194 │   else:                                                                                  │
│   195 │   │   predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device))          │
│   196 │   image = cv2.imread(image_path)               
I place the weights file in Grounded-Segment-Anything 
and use      
python grounded_sam_demo.py \
  --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py \
  --grounded_checkpoint groundingdino_swint_ogc.pth \
  --sam_hq_checkpoint sam_hq_vit_h.pth \
  --use_sam_hq \
  --input_image sam_hq_demo_image.png \
  --output_dir "outputs" \
  --box_threshold 0.3 \
  --text_threshold 0.25 \
  --text_prompt "chair." \
  --device "cuda"

**Comment by rentainhe** [comment]
> > We've updated the `segment_anything` dir, you should reinstall sam before running the demo
> 
> After I tried to re-download, the problem changed to "filename 'storages' not found" 190 │ │ │ 191 │ # initialize SAM │ │ 192 │ if use_sam_hq: │ │ ❱ 193 │ │ predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(device)) │ │ 194 │ else: │ │ 195 │ │ predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device)) │ │ 196 │ image = cv2.imread(image_path) I place the weights file in Grounded-Segment-Anything and use python grounded_sam_demo.py --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py --grounded_checkpoint groundingdino_swint_ogc.pth --sam_hq_checkpoint sam_hq_vit_h.pth --use_sam_hq --input_image sam_hq_demo_image.png --output_dir "outputs" --box_threshold 0.3 --text_threshold 0.25 --text_prompt "chair." --device "cuda"

have you downloaded the pretrained weights to your local dir or not?

**Comment by MrTHMX** [comment]
> Would you like to provide more logging info about this issue~

╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/grounded_sam_demo.py:193  │
│ in <module>                                                                              │
│                                                                                          │
│   190 │                                                                                  │
│   191 │   # initialize SAM                                                               │
│   192 │   if use_sam_hq:                                                                 │
│ ❱ 193 │   │   predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(dev │
│   194 │   else:                                                                          │
│   195 │   │   predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device))  │
│   196 │   image = cv2.imread(image_path)                                                 │
│                                                                                          │
│ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │
│ anything/build_sam_hq.py:15 in build_sam_hq_vit_h                                        │
│                                                                                          │
│    12                                                                                    │
│    13                                                                                    │
│    14 def build_sam_hq_vit_h(checkpoint=None):                                           │
│ ❱  15 │   return _build_sam(                                                             │
│    16 │   │   encoder_embed_dim=1280,                                                    │
│    17 │   │   encoder_depth=32,                                                          │
│    18 │   │   encoder_num_heads=16,                                                      │
│                                                                                          │
│ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │
│ anything/build_sam_hq.py:106 in _build_sam                                               │
│                                                                                          │
│   103 │   # sam.eval()                                                                   │
│   104 │   if checkpoint is not None:                                                     │
│   105 │   │   with open(checkpoint, "rb") as f:                                          │
│ ❱ 106 │   │   │   state_dict = torch.load(f)                                             │
│   107 │   │   info = sam.load_state_dict(state_dict, strict=False)                       │
│   108 │   │   print(info)                                                                │
│   109 │   for n, p in sam.named_parameters():                                            │
│                                                                                          │
│ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │
│ :713 in load                                                                             │
│                                                                                          │
│    710 │   │   │   │   │   opened_file.seek(orig_position)                               │
│    711 │   │   │   │   │   return torch.jit.load(opened_file)                            │
│    712 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module, **pickl │
│ ❱  713 │   │   return _legacy_load(opened_file, map_location, pickle_module, **pickle_lo │
│    714                                                                                   │
│    715                                                                                   │
│    716 # Register pickling support for layout instances such as                          │
│                                                                                          │
│ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │
│ :905 in _legacy_load                                                                     │
│                                                                                          │
│    902 │   │   # legacy_load requires that f has fileno()                                │
│    903 │   │   # only if offset is zero we can attempt the legacy tar file loader        │
│    904 │   │   try:                                                                      │
│ ❱  905 │   │   │   return legacy_load(f)                                                 │
│    906 │   │   except tarfile.TarError:                                                  │
│    907 │   │   │   if _is_zipfile(f):                                                    │
│    908 │   │   │   │   # .zip is used for torch.jit.save and will throw an un-pickling e │
│                                                                                          │
│ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │
│ :802 in legacy_load                                                                      │
│                                                                                          │
│    799 │   │   with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT │
│    800 │   │   │   │   mkdtemp() as tmpdir:                                              │
│    801 │   │   │                                                                         │
│ ❱  802 │   │   │   tar.extract('storages', path=tmpdir)                                  │
│    803 │   │   │   with open(os.path.join(tmpdir, 'storages'), 'rb', 0) as f:            │
│    804 │   │   │   │   num_storages = pickle_module.load(f, **pickle_load_args)          │
│    805 │   │   │   │   for i in range(num_storages):                                     │
│                                                                                          │
│ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:2077 in extract           │
│                                                                                          │
│   2074 │   │   self._check("r")                                                          │
│   2075 │   │                                                                             │
│   2076 │   │   if isinstance(member, str):                                               │
│ ❱ 2077 │   │   │   tarinfo = self.getmember(member)                                      │
│   2078 │   │   else:                                                                     │
│   2079 │   │   │   tarinfo = member                                                      │
│   2080                                                                                   │
│                                                                                          │
│ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:1799 in getmember         │
│                                                                                          │
│   1796 │   │   """                                                                       │
│   1797 │   │   tarinfo = self._getmember(name.rstrip('/'))                               │
│   1798 │   │   if tarinfo is None:                                                       │
│ ❱ 1799 │   │   │   raise KeyError("filename %r not found" % name)                        │
│   1800 │   │   return tarinfo                                                            │
│   1801 │                                                                                 │
│   1802 │   def getmembers(self):                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: "filename 'storages' not found"

**Comment by rentainhe** [comment]
> > Would you like to provide more logging info about this issue~
> 
> ╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/grounded_sam_demo.py:193 │ │ in │ │ │ │ 190 │ │ │ 191 │ # initialize SAM │ │ 192 │ if use_sam_hq: │ │ ❱ 193 │ │ predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(dev │ │ 194 │ else: │ │ 195 │ │ predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device)) │ │ 196 │ image = cv2.imread(image_path) │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:15 in build_sam_hq_vit_h │ │ │ │ 12 │ │ 13 │ │ 14 def build_sam_hq_vit_h(checkpoint=None): │ │ ❱ 15 │ return _build_sam( │ │ 16 │ │ encoder_embed_dim=1280, │ │ 17 │ │ encoder_depth=32, │ │ 18 │ │ encoder_num_heads=16, │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:106 in _build_sam │ │ │ │ 103 │ # sam.eval() │ │ 104 │ if checkpoint is not None: │ │ 105 │ │ with open(checkpoint, "rb") as f: │ │ ❱ 106 │ │ │ state_dict = torch.load(f) │ │ 107 │ │ info = sam.load_state_dict(state_dict, strict=False) │ │ 108 │ │ print(info) │ │ 109 │ for n, p in sam.named_parameters(): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :713 in load │ │ │ │ 710 │ │ │ │ │ opened_file.seek(orig_position) │ │ 711 │ │ │ │ │ return torch.jit.load(opened_file) │ │ 712 │ │ │ │ return _load(opened_zipfile, map_location, pickle_module, **pickl │ │ ❱ 713 │ │ return _legacy_load(opened_file, map_location, pickle_module, **pickle_lo │ │ 714 │ │ 715 │ │ 716 # Register pickling support for layout instances such as │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :905 in _legacy_load │ │ │ │ 902 │ │ # legacy_load requires that f has fileno() │ │ 903 │ │ # only if offset is zero we can attempt the legacy tar file loader │ │ 904 │ │ try: │ │ ❱ 905 │ │ │ return legacy_load(f) │ │ 906 │ │ except tarfile.TarError: │ │ 907 │ │ │ if _is_zipfile(f): │ │ 908 │ │ │ │ # .zip is used for torch.jit.save and will throw an un-pickling e │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :802 in legacy_load │ │ │ │ 799 │ │ with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT │ │ 800 │ │ │ │ mkdtemp() as tmpdir: │ │ 801 │ │ │ │ │ ❱ 802 │ │ │ tar.extract('storages', path=tmpdir) │ │ 803 │ │ │ with open(os.path.join(tmpdir, 'storages'), 'rb', 0) as f: │ │ 804 │ │ │ │ num_storages = pickle_module.load(f, **pickle_load_args) │ │ 805 │ │ │ │ for i in range(num_storages): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:2077 in extract │ │ │ │ 2074 │ │ self._check("r") │ │ 2075 │ │ │ │ 2076 │ │ if isinstance(member, str): │ │ ❱ 2077 │ │ │ tarinfo = self.getmember(member) │ │ 2078 │ │ else: │ │ 2079 │ │ │ tarinfo = member │ │ 2080 │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:1799 in getmember │ │ │ │ 1796 │ │ """ │ │ 1797 │ │ tarinfo = self._getmember(name.rstrip('/')) │ │ 1798 │ │ if tarinfo is None: │ │ ❱ 1799 │ │ │ raise KeyError("filename %r not found" % name) │ │ 1800 │ │ return tarinfo │ │ 1801 │ │ │ 1802 │ def getmembers(self): │ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ KeyError: "filename 'storages' not found"

Please check the PyTorch version, we use PyTorch 1.12 or 1.13 for Grounded-SAM

**Comment by MrTHMX** [comment]
> > > Would you like to provide more logging info about this issue~
> > 
> > 
> > ╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/grounded_sam_demo.py:193 │ │ in │ │ │ │ 190 │ │ │ 191 │ # initialize SAM │ │ 192 │ if use_sam_hq: │ │ ❱ 193 │ │ predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(dev │ │ 194 │ else: │ │ 195 │ │ predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device)) │ │ 196 │ image = cv2.imread(image_path) │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:15 in build_sam_hq_vit_h │ │ │ │ 12 │ │ 13 │ │ 14 def build_sam_hq_vit_h(checkpoint=None): │ │ ❱ 15 │ return _build_sam( │ │ 16 │ │ encoder_embed_dim=1280, │ │ 17 │ │ encoder_depth=32, │ │ 18 │ │ encoder_num_heads=16, │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:106 in _build_sam │ │ │ │ 103 │ # sam.eval() │ │ 104 │ if checkpoint is not None: │ │ 105 │ │ with open(checkpoint, "rb") as f: │ │ ❱ 106 │ │ │ state_dict = torch.load(f) │ │ 107 │ │ info = sam.load_state_dict(state_dict, strict=False) │ │ 108 │ │ print(info) │ │ 109 │ for n, p in sam.named_parameters(): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :713 in load │ │ │ │ 710 │ │ │ │ │ opened_file.seek(orig_position) │ │ 711 │ │ │ │ │ return torch.jit.load(opened_file) │ │ 712 │ │ │ │ return _load(opened_zipfile, map_location, pickle_module, **pickl │ │ ❱ 713 │ │ return _legacy_load(opened_file, map_location, pickle_module, **pickle_lo │ │ 714 │ │ 715 │ │ 716 # Register pickling support for layout instances such as │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :905 in _legacy_load │ │ │ │ 902 │ │ # legacy_load requires that f has fileno() │ │ 903 │ │ # only if offset is zero we can attempt the legacy tar file loader │ │ 904 │ │ try: │ │ ❱ 905 │ │ │ return legacy_load(f) │ │ 906 │ │ except tarfile.TarError: │ │ 907 │ │ │ if _is_zipfile(f): │ │ 908 │ │ │ │ # .zip is used for torch.jit.save and will throw an un-pickling e │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :802 in legacy_load │ │ │ │ 799 │ │ with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT │ │ 800 │ │ │ │ mkdtemp() as tmpdir: │ │ 801 │ │ │ │ │ ❱ 802 │ │ │ tar.extract('storages', path=tmpdir) │ │ 803 │ │ │ with open(os.path.join(tmpdir, 'storages'), 'rb', 0) as f: │ │ 804 │ │ │ │ num_storages = pickle_module.load(f, **pickle_load_args) │ │ 805 │ │ │ │ for i in range(num_storages): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:2077 in extract │ │ │ │ 2074 │ │ self._check("r") │ │ 2075 │ │ │ │ 2076 │ │ if isinstance(member, str): │ │ ❱ 2077 │ │ │ tarinfo = self.getmember(member) │ │ 2078 │ │ else: │ │ 2079 │ │ │ tarinfo = member │ │ 2080 │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:1799 in getmember │ │ │ │ 1796 │ │ """ │ │ 1797 │ │ tarinfo = self._getmember(name.rstrip('/')) │ │ 1798 │ │ if tarinfo is None: │ │ ❱ 1799 │ │ │ raise KeyError("filename %r not found" % name) │ │ 1800 │ │ return tarinfo │ │ 1801 │ │ │ 1802 │ def getmembers(self): │ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ KeyError: "filename 'storages' not found"
> 
> Please check the PyTorch version, we use PyTorch 1.12 or 1.13 for Grounded-SAM

my PyTorch version is 1.12.1

**Comment by MrTHMX** [comment]
> > > > Would you like to provide more logging info about this issue~
> > > 
> > > 
> > > ╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/grounded_sam_demo.py:193 │ │ in │ │ │ │ 190 │ │ │ 191 │ # initialize SAM │ │ 192 │ if use_sam_hq: │ │ ❱ 193 │ │ predictor = SamPredictor(build_sam_hq(checkpoint=sam_hq_checkpoint).to(dev │ │ 194 │ else: │ │ 195 │ │ predictor = SamPredictor(build_sam(checkpoint=sam_checkpoint).to(device)) │ │ 196 │ image = cv2.imread(image_path) │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:15 in build_sam_hq_vit_h │ │ │ │ 12 │ │ 13 │ │ 14 def build_sam_hq_vit_h(checkpoint=None): │ │ ❱ 15 │ return _build_sam( │ │ 16 │ │ encoder_embed_dim=1280, │ │ 17 │ │ encoder_depth=32, │ │ 18 │ │ encoder_num_heads=16, │ │ │ │ /home/evsjtu2/disk1/gumingxiang/GSAM/Grounded-Segment-Anything/segment_anything/segment_ │ │ anything/build_sam_hq.py:106 in _build_sam │ │ │ │ 103 │ # sam.eval() │ │ 104 │ if checkpoint is not None: │ │ 105 │ │ with open(checkpoint, "rb") as f: │ │ ❱ 106 │ │ │ state_dict = torch.load(f) │ │ 107 │ │ info = sam.load_state_dict(state_dict, strict=False) │ │ 108 │ │ print(info) │ │ 109 │ for n, p in sam.named_parameters(): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :713 in load │ │ │ │ 710 │ │ │ │ │ opened_file.seek(orig_position) │ │ 711 │ │ │ │ │ return torch.jit.load(opened_file) │ │ 712 │ │ │ │ return _load(opened_zipfile, map_location, pickle_module, **pickl │ │ ❱ 713 │ │ return _legacy_load(opened_file, map_location, pickle_module, **pickle_lo │ │ 714 │ │ 715 │ │ 716 # Register pickling support for layout instances such as │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :905 in _legacy_load │ │ │ │ 902 │ │ # legacy_load requires that f has fileno() │ │ 903 │ │ # only if offset is zero we can attempt the legacy tar file loader │ │ 904 │ │ try: │ │ ❱ 905 │ │ │ return legacy_load(f) │ │ 906 │ │ except tarfile.TarError: │ │ 907 │ │ │ if _is_zipfile(f): │ │ 908 │ │ │ │ # .zip is used for torch.jit.save and will throw an un-pickling e │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/site-packages/torch/serialization.py │ │ :802 in legacy_load │ │ │ │ 799 │ │ with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT │ │ 800 │ │ │ │ mkdtemp() as tmpdir: │ │ 801 │ │ │ │ │ ❱ 802 │ │ │ tar.extract('storages', path=tmpdir) │ │ 803 │ │ │ with open(os.path.join(tmpdir, 'storages'), 'rb', 0) as f: │ │ 804 │ │ │ │ num_storages = pickle_module.load(f, **pickle_load_args) │ │ 805 │ │ │ │ for i in range(num_storages): │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:2077 in extract │ │ │ │ 2074 │ │ self._check("r") │ │ 2075 │ │ │ │ 2076 │ │ if isinstance(member, str): │ │ ❱ 2077 │ │ │ tarinfo = self.getmember(member) │ │ 2078 │ │ else: │ │ 2079 │ │ │ tarinfo = member │ │ 2080 │ │ │ │ /home/evsjtu2/miniconda3/envs/gmx-sam/lib/python3.9/tarfile.py:1799 in getmember │ │ │ │ 1796 │ │ """ │ │ 1797 │ │ tarinfo = self._getmember(name.rstrip('/')) │ │ 1798 │ │ if tarinfo is None: │ │ ❱ 1799 │ │ │ raise KeyError("filename %r not found" % name) │ │ 1800 │ │ return tarinfo │ │ 1801 │ │ │ 1802 │ def getmembers(self): │ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ KeyError: "filename 'storages' not found"
> > 
> > 
> > Please check the PyTorch version, we use PyTorch 1.12 or 1.13 for Grounded-SAM
> 
> my PyTorch version is 1.12.1
The code works fine without using SAM-HQ

**Comment by rentainhe** [comment]
I will check it later

**Comment by MrTHMX** [comment]
> I will check it later

thanks a lot

**Comment by rentainhe** [comment]
Sry I can not reproduce this problem, this is my environment:

```bash
Package                Version            Editable project location
---------------------- ------------------ ---------------------------------------------------------------------
accelerate             0.17.0
addict                 2.4.0
aiofiles               23.1.0
aiohttp                3.8.4
aiosignal              1.3.1
altair                 5.0.0
antlr4-python3-runtime 4.9.3
anyio                  3.6.2
asttokens              2.2.1
async-timeout          4.0.2
attrs                  23.1.0
av                     10.0.0
backcall               0.2.0
beautifulsoup4         4.11.2
brotlipy               0.7.0
certifi                2022.12.7
cffi                   1.15.1
charset-normalizer     2.0.4
click                  7.1.2
clip                   1.0
cmake                  3.26.3
comm                   0.1.3
contourpy              1.0.7
cryptography           39.0.1
cycler                 0.11.0
debugpy                1.6.7
decorator              5.1.1
deepfloyd-if           1.0.2rc0
diffusers              0.14.0
einops                 0.6.1
exceptiongroup         1.1.1
executing              1.2.0
fairscale              0.4.13
fastapi                0.95.1
ffmpy                  0.3.0
filelock               3.12.0
Flask                  1.1.4
Flask-Cors             3.0.10
flaskwebgui            0.3.5
fonttools              4.39.3
frozenlist             1.3.3
fsspec                 2023.4.0
ftfy                   6.1.1
fvcore                 0.1.5.post20221221
gradio                 3.30.0
gradio_client          0.2.4
groundingdino          0.1.0              /code/Grounded-Segment-Anything/GroundingDINO
h11                    0.14.0
httpcore               0.17.0
httpx                  0.24.0
huggingface-hub        0.14.1
idna                   3.4
imageio                2.28.1
importlib-metadata     6.6.0
iniconfig              2.0.0
iopath                 0.1.10
ipykernel              6.23.0
ipython                8.13.2
itsdangerous           1.1.0
jedi                   0.18.2
Jinja2                 2.11.3
joblib                 1.2.0
jsonschema             4.17.3
jupyter_client         8.2.0
jupyter_core           5.3.0
kiwisolver             1.4.4
lama-cleaner           1.1.2
lazy_loader            0.2
linkify-it-py          2.0.2
lit                    16.0.3
loguru                 0.7.0
markdown-it-py         2.2.0
MarkupSafe             2.0.1
matplotlib             3.7.1
matplotlib-inline      0.1.6
mdit-py-plugins        0.3.3
mdurl                  0.1.2
mkl-fft                1.3.6
mkl-random             1.2.2
mkl-service            2.4.0
multidict              6.0.4
nest-asyncio           1.5.6
networkx               3.1
nltk                   3.8.1
numpy                  1.24.3
omegaconf              2.3.0
openai                 0.27.6
opencv-python          4.7.0.72
orjson                 3.8.12
packaging              23.1
pandas                 2.0.1
parameterized          0.9.0
parso                  0.8.3
pexpect                4.8.0
pickleshare            0.7.5
piexif                 1.1.3
Pillow                 9.4.0
pip                    23.0.1
platformdirs           3.5.1
pluggy                 1.0.0
portalocker            2.7.0
prompt-toolkit         3.0.38
protobuf               3.20.1
psutil                 5.9.5
ptyprocess             0.7.0
pure-eval              0.2.2
pycocotools            2.0.6
pycparser              2.21
pydantic               1.10.7
pydub                  0.25.1
Pygments               2.15.1
pyOpenSSL              23.0.0
pyparsing              3.0.9
pyrsistent             0.19.3
PySocks                1.7.1
pytest                 7.3.1
python-dateutil        2.8.2
python-multipart       0.0.6
pytorchvideo           0.1.5
pytz                   2023.3
PyWavelets             1.4.1
PyYAML                 6.0
pyzmq                  25.0.2
regex                  2023.5.5
requests               2.29.0
rich                   13.3.5
safetensors            0.3.1
scikit-image           0.19.3
scikit-learn           1.2.2
scipy                  1.10.1
seaborn                0.12.2
segment-anything       1.0                /code/Grounded-Segment-Anything/segment_anything
semantic-version       2.10.0
sentencepiece          0.1.99
setuptools             66.0.0
six                    1.16.0
sniffio                1.3.0
soupsieve              2.4.1
stack-data             0.6.2
starlette              0.26.1
supervision            0.6.0
tabulate               0.9.0
termcolor              2.3.0
threadpoolctl          3.1.0
tifffile               2023.4.12
timm                   0.6.13
tokenizers             0.13.3
tomli                  2.0.1
toolz                  0.12.0
torch                  1.12.1
torchaudio             0.12.1
torchvideo             0.0.0
torchvision            0.13.1
tornado                6.3.2
tqdm                   4.65.0
traitlets              5.9.0
transformers           4.27.4
triton                 2.0.0.post1
typing_extensions      4.5.0
tzdata                 2023.3
uc-micro-py            1.0.2
ultralytics            8.0.120
urllib3                1.26.15
uvicorn                0.22.0
wcwidth                0.2.6
websockets             11.0.3
Werkzeug               1.0.1
wheel                  0.38.4
whichcraft             0.6.1
xformers               0.0.19
yacs                   0.1.8
yapf                   0.33.0
yarl                   1.9.2
zipp                   3.15.0
```

**Comment by MrTHMX** [comment]
I solved the problem by re-downloading the weight file of hq, maybe my previous weight file was damaged, thank you for your help!

**Comment by rentainhe** [comment]
> I solved the problem by re-downloading the weight file of hq, maybe my previous weight file was damaged, thank you for your help!

You're welcome, I'm going to close this issue, feel free to reopen it if necessary~
