### ISSUE TITLE
I have some questions.

### ISSUE THREAD

**Issue by autumnDrinking** [IDEA-Research/Grounded-Segment-Anything#329]
If I encounter such a situation but have followed the process, what should I do at this point?
My command input is: TRANSFORMERS_OFFLINE=1 python grounding_dino_demo.py --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py --grounded_checkpoint groundingdino_swint_ogc.pth --input_image assets/demo1.jpg --output_dir 'outputs' --box_threshold 0.3 --text_threshold 0.25 --text_prompt 'bear' --device 'cuda'

![207533fae4ff2b747e04381bdb80fbd](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/118439102/5effbe24-5a2d-4012-af46-5307ad5452be)

**Comment by rentainhe** [comment]
> If I encounter such a situation but have followed the process, what should I do at this point? My command input is: TRANSFORMERS_OFFLINE=1 python grounding_dino_demo.py --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py --grounded_checkpoint groundingdino_swint_ogc.pth --input_image assets/demo1.jpg --output_dir 'outputs' --box_threshold 0.3 --text_threshold 0.25 --text_prompt 'bear' --device 'cuda'
> 
> ![207533fae4ff2b747e04381bdb80fbd](https://user-images.githubusercontent.com/118439102/250587703-5effbe24-5a2d-4012-af46-5307ad5452be.png)

This maybe that you did not download all the pretrained model file from Huggingface, you can download it from this [link](https://huggingface.co/bert-base-uncased/tree/main) and put it in your local path:

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/48727989/01fa4adf-573d-42c0-92d2-68f7fdc79c03)

**Comment by autumnDrinking** [comment]
I have successfully resolved the issue. Thanks.

**Comment by rentainhe** [comment]
> I have successfully resolved the issue. Thanks.

You're welcome and I'm going to close this issue. Feel free to report issues if you meet any other questions
