### ISSUE TITLE
Typo? in title of grounded_sam.ipynb

### ISSUE THREAD

**Issue by ZhangHuixin1103** [IDEA-Research/Grounded-Segment-Anything#334]
Hi I think it should be "Grounded Segment Anything", not "Grounded Segement Anthing".

**Comment by rentainhe** [comment]
> Hi I think it should be "Grounded Segment Anything", not "Grounded Segement Anthing".

Thanks for reporting this issue, we will fix it later~

**Comment by rentainhe** [comment]
We've already fix this typo, thank you so much
