### ISSUE TITLE
program running time

### ISSUE THREAD

**Issue by nomoneyExpection** [IDEA-Research/Grounded-Segment-Anything#335]
I want to know how long it takes on average to run python grounded_sam_simple_demo.py each time, and the graphics card with 4 g can’t run

**Comment by rentainhe** [comment]
> I want to know how long it takes on average to run python grounded_sam_simple_demo.py each time, and the graphics card with 4 g can’t run

You should remove some model inference to CPU instead of GPU to avoid the GPU memory issue, as we observed on a single A100, it takes about 3-4 seconds on each image

**Comment by rentainhe** [comment]
I'm closing this issue now, feel free to reopen it if needed
