### ISSUE TITLE
difference between text_threshold and box _threshold 

### ISSUE THREAD

**Issue by D6561** [IDEA-Research/Grounded-Segment-Anything#340]
thanks for your great jobs! 
But I have a question that what's the differences between text_threshold and box _threshold.
What's their meaning in the programme?

**Comment by rentainhe** [comment]
Sry for the late reply, these two args have the meaning as:
- `text threshold`: used for control the output phrase name of each box, each box will be labeled as the text > text threshold
- `box threshold`: used to control the output box by its confidence.

**Comment by rentainhe** [comment]
I'm closing this issue now, feel free to reopen if needed
