### ISSUE TITLE
Try to use SAM_HQ, the segment seem fail !

### ISSUE THREAD

**Issue by Saoyu99** [IDEA-Research/Grounded-Segment-Anything#343]
when i try to use sam_hq, the segment make some mistake. 
i use the domo chair pic, and the sam_output is :
![grounded_sam_output](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/53813987/24e2e0f8-2dae-4ffd-98b5-d49914f53cce)
the mask is :
![mask](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/53813987/d758cafc-aaa9-41f0-87a3-75ac53043505)

my .sh file is :
export CUDA_VISIBLE_DEVICES=0
python grounded_sam_demo.py \
  --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py \
  --grounded_checkpoint groundingdino_swint_ogc.pth \
  --sam_checkpoint sam_hq_vit_b.pth \
  --use_sam_hq \
  --input_image assets/sam_hq_demo_image.png \
  --output_dir "outputs" \
  --box_threshold 0.3 \
  --text_threshold 0.25 \
  --text_prompt "chair." \
  --device "cuda"

and when i use the ori SAM, all things going to be right, is there any mistake?

**Comment by yuanxin1995** [comment]
Is your problem solved? I also encountered the same problem. The picture I used was the default parameter, and the test picture was also provided by the official data.
![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/46620769/11ce5b60-88f9-4792-8e37-a47d4acf1c87)
command: python3 grounded_sam_demo.py  --config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py  --grounded_checkpoint groundingdino_swint_ogc.pth  --sam_checkpoint sam_vit_h_4b8939.pth --input_image  ./assets/demo1.jpg   --output_dir "outputs/bear"   --box_threshold 0.3   --text_threshold 0.25   --text_prompt "bear"  --device "cuda"

**Comment by Saoyu99** [comment]
@ymq2017 thanks for the help! it works now.

**Comment by wen-yuan-zhang** [comment]
thanks a lot!
