### ISSUE TITLE
Hello, Any workable solution to this problem. I am trying to run it on MAC which does not have GPU and I get the errors related to GPU

### ISSUE THREAD

**Issue by Nidacoke** [IDEA-Research/Grounded-Segment-Anything#345]
Hello, Any workable solution to this problem. I am trying to run it on MAC which does not have GPU and I get the errors related to GPU

_Originally posted by @csv610 in https://github.com/IDEA-Research/GroundingDINO/issues/71#issuecomment-1542293997_

**Comment by rentainhe** [comment]
We support `CPU mode` for inference your demo with Grounded-SAM

**Comment by csv610** [comment]
Hello 
Can we use mps on Mac m1/m2?
Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, July 25, 2023, 6:56 AM, Ren Tianhe ***@***.***> wrote:




We support CPU mode for inference your demo with Grounded-SAM

**Comment by rentainhe** [comment]
> Hello  Can we use mps on Mac m1/m2? Thanks Sent from Yahoo Mail for iPhone On Tuesday, July 25, 2023, 6:56 AM, Ren Tianhe ***@***.***> wrote: We support CPU mode for inference your demo with Grounded-SAM — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

We did not test this situation before, maybe you can try to inference on your device to see if `Grounded-SAM` can work on it
