### ISSUE TITLE
name '_C' is not defined in jupyter with GPU

### ISSUE THREAD

**Issue by Nancis1130** [IDEA-Research/Grounded-Segment-Anything#360]
I am using groundingdino on a Jupyter with a GPU and the error is as follows:
```

 42 @staticmethod
     43 def forward(
     44     ctx,
   (...)
     50     im2col_step,
     51 ):
     52     ctx.im2col_step = im2col_step
---> 53     output = _C.ms_deform_attn_forward(
     54         value,
     55         value_spatial_shapes,
     56         value_level_start_index,
     57         sampling_locations,
     58         attention_weights,
     59         ctx.im2col_step,
     60     )
     61     ctx.save_for_backward(
     62         value,
     63         value_spatial_shapes,
   (...)
     66         attention_weights,
     67     )
     68     return output
NameError: name '_C' is not defined
```

I have tried the solutions mentioned in the relevant issues:
```
export CUDA_HOME=/usr/local/cuda-11.7/
cd GroundingDINO
python setup.py install

```
but no one worked.

My environment:
python==3.10
torch==2.0.1
cuda==11.7

Thanks for help !

**Comment by Krupal09** [comment]
I have the same issue !

**Comment by Nancis1130** [comment]
Hi @Krupal09, share my solution if you haven't solved it yet. The key is to ensure that in the CUDA environment, not the CPU, then compile and install **groundingdino** in the CUDA environment.
```
cd groundingdino
python setup.py build
python setup.py install
```
When the "_C.cpython-*.so" file appears, the installation is successful.

**Comment by Krupal09** [comment]
@Nancis1130 Thank you very much for your help 😊

Unfortunately, my system has crashed. I am waiting for it to get repaired. Sure, I shall try this solution. Appreciate it 👍

**Comment by SauceCat** [comment]
> Hi @Krupal09, share my solution if you haven't solved it yet. The key is to ensure that in the CUDA environment, not the CPU, then compile and install **groundingdino** in the CUDA environment.
> 
> ```
> cd groundingdino
> python setup.py build
> python setup.py install
> ```
> 
> When the "_C.cpython-*.so" file appears, the installation is successful.

It works like magic, thanks. 💯

**Comment by TaBeti** [comment]
@Nancis1130  It works, thank you very much.
