### ISSUE TITLE
 install.sh: line 5: python: command not found

### ISSUE THREAD

**Issue by puranjay123** [IDEA-Research/Grounded-Segment-Anything#376]
while running the install without docker commands in the README file:
running this command gives
`cd grounded-sam-osx && bash install.sh`
Attribute error:
`install.sh: line 5: python: command not found`
 it is showing Python command not found  but my system has already a Python version
  this ->`Python 3.10.12`
This is install.sh file
```
`#!/bin/bash
pip install openmim
mim install mmcv-full==1.7.1
pip install -r requirements.txt
cd transformer_utils && python setup.py install`
```

**Comment by linjing7** [comment]
Hi, you can try directly running `cd transformer_utils && python setup.py install` instead of bash install.sh. If it does not work, you can run `python3 setup.py install`.

**Comment by puranjay123** [comment]
Hi, @linjing7 thankyou for the response.
running `python3 setup.py install` seems to work for me.
