### ISSUE TITLE
如何继续训练该项目对特定物体的识别精度？

### ISSUE THREAD

**Issue by fengyin2022** [IDEA-Research/Grounded-Segment-Anything#388]
请问如果想要在当前实现效果的基础上，加强对某一种物体的识别效果，应该使用哪一种类型的训练集？怎么编写代码来训练呢？（新人小白）

**Comment by rentainhe** [comment]
可以参考开源的Grounding-DINO的训练代码，增加自己需要的数据进行训练，MMDet已经支持了，还有一个很优秀的开源[Open-Grounding-DINO](https://github.com/longzw1997/Open-GroundingDino) 可以参考使用

**Comment by fengyin2022** [comment]
好滴！非常感谢！

**Comment by rentainhe** [comment]
不客气
