### ISSUE TITLE
Some issue about the wrong segmentation when the bounding box is large and scene is simple.

### ISSUE THREAD

**Issue by Lazer2077** [IDEA-Research/Grounded-Segment-Anything#397]
感谢作者非常好的开源项目!

想请问下作者如果需要提示的物体bounding box占整张图比较大,且被提示的物体不是很规则, 就有可能会分割到其他物体上去(比如天空)有没有方法解决这个问题?

**Comment by rentainhe** [comment]
这个其实是SAM基于bounding box的分割情况下，对于边界分割的不是特别好，可以考虑用sam-hq或者手动加一些point prompt

**Comment by Lazer2077** [comment]
好的谢谢

**Comment by Nidacoke** [comment]
****
