### ISSUE TITLE
Segment result quality?

### ISSUE THREAD

**Issue by crapthings** [IDEA-Research/Grounded-Segment-Anything#401]
Why does the test result look different from what I see on the official SAM website?

<img width="1104" alt="image" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/1147704/9d51d410-6117-47e5-8cbe-3cdf73f20994">

<img width="691" alt="image" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/1147704/b991cbda-e770-44d0-bffb-0851a9f579d1">

<img width="1669" alt="image" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/1147704/7e32dc97-a22e-4aed-ae3a-dfa404fe20db">

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/1147704/0e40230c-ac0c-46ac-b12c-9c8d144e787c)

**Comment by rentainhe** [comment]
You may use `SAM-Huge` for better results
