### ISSUE TITLE
Plan about EfficientSAM?

### ISSUE THREAD

**Issue by adkAurora** [IDEA-Research/Grounded-Segment-Anything#411]
https://github.com/yformer/EfficientSAM

**Comment by rentainhe** [comment]
Sure, we will update Grounded-SAM when they release their code~

**Comment by rentainhe** [comment]
Hello @adkAurora ! We've alrealy implemented `grounded-efficient-sam` in our project, and we're going to implement `grounded-edge-sam` and `grounded-repvit-sam` in the future release
