### ISSUE TITLE
A new paper 

### ISSUE THREAD

**Issue by lwpyh** [IDEA-Research/Grounded-Segment-Anything#415]
Hi there,

We have just release our new paper "Relax Image-Specific Prompt Requirement in SAM: A Single Generic Prompt for Segmenting Camouflaged Objects", which is accepted in AAAI24, It explores how to relax the instance-specific prompt requirements in SAM. Our paper link is: https://arxiv.org/abs/2312.07374 and our code page is: https://github.com/jyLin8100/GenSAM. Would you mind to add our paper in your project collection?

**Comment by rentainhe** [comment]
Sure! We'd like to highlight it in our project, if u want, u can also create a new PR to add it! @lwpyh

**Comment by lwpyh** [comment]
> Sure! We'd like to highlight it in our project, if u want, u can also create a new PR to add it! @lwpyh

Hi Tianhe:

We have made a PR to include our work in highlight. Thank you for your support.
