### ISSUE TITLE
Can I use this project for semantic segmentation? Cause I also cares about the segmentation and the category of the background.

### ISSUE THREAD

**Issue by Luciennnnnnn** [IDEA-Research/Grounded-Segment-Anything#462]
Hi, great work! Can I use this project for semantic segmentation? Cause I also cares about the segmentation and the category of the background.

**Comment by Luciennnnnnn** [comment]
I want to achieve semantic or panoptic segmentation, if Grounded-SAM can not do this, what's the recommended model?

**Comment by rentainhe** [comment]
@Luciennnnnnn Hello, G-SAM can do panoptic segmentation tasks, you can refer to this project as a good example:
- https://github.com/segments-ai/panoptic-segment-anything

**Comment by Luciennnnnnn** [comment]
@rentainhe Hi, thank you for your recommendation, i'll take a look at it.

**Comment by Luciennnnnnn** [comment]
So if I want to achieve automatic open-vocabulary panoptic segmentation, is my current best choice RAM++ + G-SAM?

**Comment by rentainhe** [comment]
> So if I want to achieve automatic open-vocabulary panoptic segmentation, is my current best choice RAM++ + G-SAM?

Yep, maybe this is the simplest way to achieve a good result, you can visualize and double-check the results

**Comment by Luciennnnnnn** [comment]
@rentainhe That would be great! Thanks!
