### ISSUE TITLE
How to make text prompt support Non-English, like Chinese?

### ISSUE THREAD

**Issue by tangmingxing1988** [IDEA-Research/Grounded-Segment-Anything#465]
I have a problem with the text prompt, it could not be Chinese, or the result makes nonsense. I have to translate Chinse To English to make it work, and it works very well. So, is there a way to use Chinese text prompt directly?

**Comment by rentainhe** [comment]
Hello, Grounding-DINO did not support Chinese prompt, maybe you can use a translator to translate your prompt into English first

**Comment by tangmingxing1988** [comment]
> Hello, Grounding-DINO did not support Chinese prompt, maybe you can use a translator to translate your prompt into English first

Thank you. Can you suggest a translator or dictionary for this? For example, like database for category names etc. Because ordinary translator is two slow for this.

**Comment by tangmingxing1988** [comment]
I end up using translator and the speed is acceptable, thanks and I will close this issue.
