### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'bert_base_uncased_path'

### ISSUE THREAD

**Issue by piclez** [IDEA-Research/Grounded-Segment-Anything#525]
Getting this error running on my WSL machine:
```
Traceback (most recent call last):
    self.dino_model = load_model(
                      ^^^^^^^^^^^
  File "/home/peter/workspace/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py", line 32, in load_model
    model = build_model(args)
            ^^^^^^^^^^^^^^^^^
  File "/home/peter/workspace/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/__init__.py", line 17, in build_model
    model = build_func(args)
            ^^^^^^^^^^^^^^^^
  File "/home/peter/workspace/Grounded-Segment-Anything/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 377, in build_groundingdino
    bert_base_uncased_path=args.bert_base_uncased_path,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/workspace/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/slconfig.py", line 327, in __getattr__
    return getattr(self._cfg_dict, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/workspace/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/slconfig.py", line 39, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'bert_base_uncased_path'
```

Could be related to this commit @jackyjinjing ?
https://github.com/IDEA-Research/Grounded-Segment-Anything/commit/37c249804f4334dd39c2b28b142ba373ae2342ae

**Comment by rentainhe** [comment]
I think you should set a default value in config to avoid this issue @jackyjinjing

**Comment by rentainhe** [comment]
I will solve this issue this week, please stay tuned @piclez , if you have already solved it in your local env, you can propose a new PR for this issue and we will merge it as soon as possible.

**Comment by erikbwu** [comment]
For a quick fix, what worked for me was add bert-base_uncased_path to GroundingDINO_SwinT_OGC.py or whatever config file you use for DINO:

`batch_size = 1
modelname = "groundingdino"
backbone = "swin_T_224_1k"
position_embedding = "sine"
pe_temperatureH = 20
pe_temperatureW = 20
return_interm_indices = [1, 2, 3]
backbone_freeze_keywords = None
enc_layers = 6
dec_layers = 6
pre_norm = False
dim_feedforward = 2048
hidden_dim = 256
dropout = 0.0
nheads = 8
num_queries = 900
query_dim = 4
num_patterns = 0
num_feature_levels = 4
enc_n_points = 4
dec_n_points = 4
two_stage_type = "standard"
two_stage_bbox_embed_share = False
two_stage_class_embed_share = False
transformer_activation = "relu"
dec_pred_bbox_embed_share = True
dn_box_noise_scale = 1.0
dn_label_noise_ratio = 0.5
dn_label_coef = 1.0
dn_bbox_coef = 1.0
embed_init_tgt = True
dn_labelbook_size = 2000
max_text_len = 256
text_encoder_type = "bert-base-uncased"
use_text_enhancer = True
use_fusion_layer = True
use_checkpoint = True
use_transformer_ckpt = True
use_text_cross_attention = True
text_dropout = 0.0
fusion_dropout = 0.0
fusion_droppath = 0.1
sub_sentence_present = True
bert_base_uncased_path = None
`

**Comment by jackyjinjing** [comment]
Sorry for that，it's my fault，I will fix it ASAP
