### ISSUE TITLE
automatic_label_ram_demo device problem

### ISSUE THREAD

**Issue by zdshang** [IDEA-Research/Grounded-Segment-Anything#530]
① When I run the demo code and set the parameter to --device 'cuda:2', an error will be reported: RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
But when I change the code to
```
# device = args.device
bert_base_uncased_path = args.bert_base_uncased_path

if args.device == "cpu":
device = torch.device("cpu")
elif args.device.startswith('cuda:'):
device_id = int(args.device.split(':')[1])
device = torch.device("cuda:" + str(device_id))
torch.cuda.set_device(device_id)
else:
raise ValueError(
"Invalid device specified in --device. Expected 'cpu' or 'cuda:<device_id>', but got " + args.device)
```

The program works fine
I use: single NVIDIA RTX A6000, cuda 12.1, driver version 535.183.01, pytorch version 2.4.1

② Part of this code will download bert_base_uncased by default, even after the modification according to #517
Modification method: Change line 131 in recognize-anything/ram/models/utils.py, text_encoder_type, to the downloaded bert_base_uncased path

**Comment by HAOYON-666** [comment]
May I ask how to solve this? I also encountered the same problem
