### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by mickelliu** [IDEA-Research/Grounded-Segment-Anything#60]
Got error when using the gradio app. The webUI functions normally but will get this error when I asked it to performa segmentation on a provided image (e.g. demo1.jpg, the one with many bears)

```
  File "/mnt/d/Code/Grounded-Segment-Anything/gradio_app.py", line 179, in run_grounded_sam
    model = load_model_hf(config_file, ckpt_repo_id, ckpt_filenmae)
  File "/mnt/d/Code/Grounded-Segment-Anything/gradio_app.py", line 39, in load_model_hf
    checkpoint = torch.load(cache_file, map_location='cuda:0')
  File "/home/XJP/Miniconda3/envs/grounded-SAM/lib/python3.10/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/XJP/Miniconda3/envs/grounded-SAM/lib/python3.10/site-packages/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

Things I have tried so far:
- Removed and re-created new conda environments
- Installed lower version of torch (tried 1.8 and 2.0)
- Installed lower version of gradio (tried 3.25 and 3.18)

Running the provided python commands are perfectly fine. I suspect that it has something to do with gradio.

OS: WSL
Python Version: 3.10

**Comment by sunshineywz123** [comment]
> 

请问下你是怎么解决的？

**Comment by mickelliu** [comment]
> > 
> 
> 请问下你是怎么解决的？

I actually forgot how I got around it. I probably cleaned up huggingface related files under the .cache folder.
