### ISSUE TITLE
cannot import name 'build_sam' from 'segment_anything' (unknown location)

### ISSUE THREAD

**Issue by WalterWangRevo** [IDEA-Research/Grounded-Segment-Anything#85]
Hello, when I run Grounded-Segment-Anything Demo in my vscode, the error is "Traceback (most recent call last):
  File "grounded_sam_demo.py", line 18, in <module>
    from segment_anything import build_sam, SamPredictor 
ImportError: cannot import name 'build_sam' from 'segment_anything' (unknown location)"

**Comment by Dandelionym** [comment]
hi, Revo, I guess you forgot to install segment_anything following the official instruction. BTY, you could check the import clause if it is correctly find the packages.

change `from segment_anything import build_sam, SamPredictor` to `from segment_anything.segment_anything import build_sam, SamPredictor` may be a quick way to solve this.

**Comment by WalterWangRevo** [comment]
> hi, Revo, I guess you forgot to install segment_anything following the official instruction. BTY, you could check the import clause if it is correctly find the packages.
> 
> change `from segment_anything import build_sam, SamPredictor` to `from segment_anything.segment_anything import build_sam, SamPredictor` may be a quick way to solve this.

Thank you, I download the whole project (Grounded-Segment-Anything) with 'git clone' because I find the official instruction "python -m pip install -e segment_anything" is not ok. And I 'change from segment_anything import build_sam, SamPredictor to from segment_anything.segment_anything import build_sam, SamPredictor' , it seems the previous problem is solved but the new error is:
File "grounded_sam_demo.py", line 18, in <module>
    from segment_anything.segment_anything import build_sam, SamPredictor 
  File "xxx/Grounded-Segment-Anything/segment_anything/segment_anything/__init__.py", line 14, in <module>
    from .predictor import SamPredictor
  File "xxx/Grounded-Segment-Anything/segment_anything/segment_anything/predictor.py", line 10, in <module>
    from segment_anything.modeling import Sam
ModuleNotFoundError: No module named 'segment_anything.modeling'
BTW, I am all in the directory 'Grounded-Segment-Anything'.

**Comment by WalterWangRevo** [comment]
> > hi, Revo, I guess you forgot to install segment_anything following the official instruction. BTY, you could check the import clause if it is correctly find the packages.
> > change `from segment_anything import build_sam, SamPredictor` to `from segment_anything.segment_anything import build_sam, SamPredictor` may be a quick way to solve this.
> 
> Thank you, I download the whole project (Grounded-Segment-Anything) with 'git clone' because I find the official instruction "python -m pip install -e segment_anything" is not ok. And I 'change from segment_anything import build_sam, SamPredictor to from segment_anything.segment_anything import build_sam, SamPredictor' , it seems the previous problem is solved but the new error is: File "grounded_sam_demo.py", line 18, in from segment_anything.segment_anything import build_sam, SamPredictor File "xxx/Grounded-Segment-Anything/segment_anything/segment_anything/**init**.py", line 14, in from .predictor import SamPredictor File "xxx/Grounded-Segment-Anything/segment_anything/segment_anything/predictor.py", line 10, in from segment_anything.modeling import Sam ModuleNotFoundError: No module named 'segment_anything.modeling' BTW, I am all in the directory 'Grounded-Segment-Anything'.

I finally solve this problem by change `
from segment_anything.modeling import Sam` to `from segment_anything.segment_anything.modeling import Sam` in line 10 of Grounded-Segment-Anything/segment_anything/segment_anything/predictor.py

**Comment by Nidacoke** [comment]
#84
