### ISSUE TITLE
What is the version of the transformers library

### ISSUE THREAD

**Issue by SevenTae** [IDEA-Research/Grounded-Segment-Anything#94]
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
module 'distutils' has no attribute 'version'
我的transformers版本是4.27.4 是版本太高了吗，需要适合什么版本

**Comment by rentainhe** [comment]
I use `transformers 4.27.4` and maybe there some other errors in your env I think

**Comment by rentainhe** [comment]
I'm going to close this issue, feel free to reopen it if necessary
