### ISSUE TITLE
gradio_app 如何修改成加载本地的model文件

### ISSUE THREAD

**Issue by LeanFly** [IDEA-Research/Grounded-Segment-Anything#95]
```
config_file = 'GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py'
ckpt_repo_id = "ShilongLiu/GroundingDINO"
ckpt_filenmae = "groundingdino_swint_ogc.pth"
sam_checkpoint='sam_vit_h_4b8939.pth' 
output_dir="outputs"
device="cuda"
```
如上，现在gradio_app配置的是每次运行都要请求huggingface的文件，鉴于本地网络访问huggingface不是很稳定，我想改成请求本地model文件该如何配置呢？

**Comment by tuofeilunhifi** [comment]
你可以直接将模型下载到本地，然后我在模型加载那一块有个注释，可以用本地加载的方法

**Comment by LeanFly** [comment]
> 你可以直接将模型下载到本地，然后我在模型加载那一块有个注释，可以用本地加载的方法

我翻了下报错的log，主要是这个函数请求远程文件时出现的网络报错
`def load_model_hf(model_config_path, repo_id, filename, device='cpu'):
    args = SLConfig.fromfile(model_config_path) 
    model = build_model(args)
    args.device = device

    cache_file = hf_hub_download(repo_id=repo_id, filename=filename)
    checkpoint = torch.load(cache_file, map_location='cpu')
    log = model.load_state_dict(clean_state_dict(checkpoint['model']), strict=False)
    print("Model loaded from {} \n => {}".format(cache_file, log))
    _ = model.eval()
    return model`

**Comment by xiaowenhe** [comment]
可能需要修改代码，才能加载本地模型，目前看好像必须联网，build_model这个函数开始需要下载一些其他文件。希望可以给个参考，需要下载哪些文件，如何修改配置文件路径和代码，这样就可以不联网运行了。谢谢！

**Comment by LeanFly** [comment]
> 可能需要修改代码，才能加载本地模型，目前看好像必须联网，build_model这个函数开始需要下载一些其他文件。希望可以给个参考，需要下载哪些文件，如何修改配置文件路径和代码，这样就可以不联网运行了。谢谢！

通过debug的方式来看是代码逻辑的处理方面加了远程请求，需要追踪调整，有点儿难搞

**Comment by hukaick** [comment]
两种方法
1.去Huggface 。你看你哪个模型卡住了，找哪个自己下载，from_pretrained()填入本地路径即可，如果你网络报错就翻墙去下找个缺的模型
2.加入cache_dir

**Comment by LeanFly** [comment]
> 你可以直接将模型下载到本地，然后我在模型加载那一块有个注释，可以用本地加载的方法

调试了一下，找到了模型加载的路径，将文件复制出来，指定为本地的地址确实没有再请求远程文件。

是在 load_model_hf 这个方法里的 cache_file 这里，cache_file 调用了 hf_hub_download 方法下载模型文件，具体的保存地址可以直接 print(cache_file) 来获取，然后将 cache_file 指定为本地的文件即可

![image](https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/18253047/7df19a27-8e88-4f67-9769-a5af89329368)
